name: Geocode Address Chunks

on:
  workflow_dispatch:

jobs:
  geocode:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ["031", "032", "033"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run geocoding script
        run: |
          python geocode.py master${{ matrix.file }}.csv output${{ matrix.file }}.csv

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: geocoded-${{ matrix.file }}
          path: output${{ matrix.file }}.csv
