name: Get LatLon from Address

on:
  workflow_dispatch:  # 手動実行

jobs:
  geocode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run geocoding script
        run: python geocode.py

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: geocoded-csv
          path: master_with_coords.csv
